# -----------------------------------------------------
# Langing Page Theme Configurations
intro_image: /img/intro-bg.jpg
banner_image: /img/banner-bg.jpg

# Navigation items
navigation:
    about: /about

social:
  - title: weibo
    url: https://www.zhihu.com/people/ming-xi-47
  - title: github
    url: https://github.com/frostming/
  - title: linkedin
    url: https://www.linkedin.com/in/%E5%B8%8C-%E6%98%8E-33452ba2

# Duoshuo comments & share
duoshuo_shortname: frostming

# Disqus
# disqus_shortname:
