# -----------------------------------------------------
# Langing Page Theme Configurations
cover_images:
  - /img/intro-bg.jpg
  - /img/about.jpg
  - /img/cat-bg.jpg
  - /img/contact-bg.jpg
  - /img/home-bg.jpg
  - /img/home-bg-o.jpg

banner_image: /img/banner-bg.jpg

# Navigation items
navigation:
    about: /about

social:
  - title:  zhihu
    url: https://www.zhihu.com/people/frostming
  - title: github
    url: https://github.com/frostming/
  - title: linkedin
    url: https://www.linkedin.com/in/%E5%B8%8C-%E6%98%8E-33452ba2
  - title: weibo
    url: http://weibo.com/frostanne

# Duoshuo comments & share
duoshuo_shortname: frostming

# Disqus
# disqus_shortname:
