# -----------------------------------------------------
# Langing Page Theme Configurations

# Navigation items
navigation:
    about: /about

social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: github
    url: https://github.com/IronSummitMedia/startbootstrap
  - title: linkedin
    url:
